In [14]:
import os

from dbase.DataAPI.ThetaData import list_dates, set_use_proxy, retrieve_chain_bulk, list_contracts
os.environ["THETADATA_USE_V3"] = "false"
set_use_proxy("")

2026-04-26 21:21:28 [test] dbase.DataAPI.ThetaData.proxy INFO: Proxy URL has been unset.

In [20]:
p={'symbol': 'NFLX', 'start_date': '20210827', 'end_date': '20210827',  'right': 'both', 'date': '20210827', 'time_of_day': '16:00:00.000', "end_time": "16:00:00.000"}

retrieve_chain_bulk(**p)

2026-04-26 19:41:40 [test] dbase.DataAPI.ThetaData.switcher INFO: Switcher call retrieve_chain_bulk -> v2

,Root,Expiration,Strike,Right,Bid_size,CloseBid,Ask_size,CloseAsk,Date,Midpoint,Weighted_midpoint
datetime,,,,,,,,,,,
2021-08-27,NFLX,2022-01-21,5.0,P,0,0.00,1,0.25,20210827,0.125,0.25000
2021-08-27,NFLX,2022-01-21,5.0,C,10,552.25,6,555.80,20210827,554.025,553.58125
2021-08-27,NFLX,2022-01-21,60.0,C,10,497.40,6,500.85,20210827,499.125,498.69375
2021-08-27,NFLX,2022-06-17,370.0,C,18,194.00,18,203.00,20210827,198.500,198.50000
2021-08-27,NFLX,2023-03-17,390.0,C,6,195.20,6,202.95,20210827,199.075,199.07500
...,...,...,...,...,...,...,...,...,...,...,...
2021-08-27,NFLX,2022-03-18,840.0,P,6,280.30,10,283.80,20210827,282.050,282.48750
2021-08-27,NFLX,2023-03-17,340.0,C,6,235.05,6,243.10,20210827,239.075,239.07500
2021-08-27,NFLX,2023-03-17,420.0,P,18,29.50,18,37.55,20210827,33.525,33.52500
2021-08-27,NFLX,2022-01-21,30.0,P,0,0.00,12,0.04,20210827,0.020,0.04000
2021-08-27,NFLX,2022-01-21,20.0,P,0,0.00,10,0.03,20210827,0.015,0.03000

In [18]:
# Data not found for the given parameters: {'symbol': 'AAPL', 'start_date': '20200826', 'end_date': '20200828', 'expiration': '20201016', 'strike': '96.25', 'right': 'C', 'url': 'http://localhost:25503/v3/option/history/eod?symbol=AAPL&start_date=20200826&end_date=20200828&expiration=20201016&strike=96.25&right=C'}
os.environ["THETADATA_USE_V3"] = "true"
d = list_dates(
    symbol='AAPL',
    exp='2020-10-16',
    right='C',
    strike=100.0,
)
d

2026-04-26 21:21:57 [test] dbase.DataAPI.ThetaData.switcher INFO: Switcher call list_dates -> v3

array(['2020-08-31', '2020-09-01', '2020-09-02', '2020-09-03',
       '2020-09-04', '2020-09-08', '2020-09-09', '2020-09-10',
       '2020-09-11', '2020-09-14', '2020-09-15', '2020-09-16',
       '2020-09-17', '2020-09-18', '2020-09-21', '2020-09-22',
       '2020-09-23', '2020-09-24', '2020-09-25', '2020-09-28',
       '2020-09-29', '2020-09-30', '2020-10-01', '2020-10-02',
       '2020-10-05', '2020-10-06', '2020-10-07', '2020-10-08',
       '2020-10-09', '2020-10-12', '2020-10-13', '2020-10-14',
       '2020-10-15', '2020-10-16'], dtype=object)

In [20]:
from trade.datamanager.utils.date import LIST_DATE_CACHE
from trade.helpers.helper import generate_option_tick_new
from trade.datamanager.option_spot import OptionSpotDataManager
from dbase.DataAPI.ThetaData import list_dates, set_use_proxy, retrieve_chain_bulk, list_contracts
len(LIST_DATE_CACHE.keys())
set_use_proxy("")
opt = generate_option_tick_new(
    symbol='AAPL',
    right='C',
    exp='2020-10-16',
    strike=96.25,
)
dm = OptionSpotDataManager("AAPL")
f = dm.get_option_spot_timeseries(
    start_date='2020-08-26',
    end_date='2020-09-28',
    expiration='2020-10-16',
    right='C',
    strike=100,
)

2026-04-26 21:22:01 [test] dbase.DataAPI.ThetaData.proxy INFO: Proxy URL has been unset.
2026-04-26 21:22:01 [test] trade.datamanager.utils INFO: Fetching date range from Thetadata for AAPL20201016C100
2026-04-26 21:22:01 [test] dbase.DataAPI.ThetaData.switcher INFO: Switcher call list_dates -> v3
2026-04-26 21:22:02 [test] trade.datamanager.utils INFO: Converting old cache data structure to new for key: symbol:AAPL|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20201016T000000|right:C|strike:100
2026-04-26 21:22:02 [test] trade.datamanager.utils INFO: No missing dates within requested range for key symbol:AAPL|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20201016T000000|right:C|strike:100. Fully covered: True
2026-04-26 21:22:02 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:AAPL|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20201016T000000|right:C|strike:100
2026-04-26 21:22:02 [test] trade.datamanager.utils INFO: Sanitizing data from 2020-08-31 00:00:00 to 2020-09-28 00:00:00...
2026-04-26 21:22:02 [test] trade.datamanager.option_spot INFO: Cache hit for option spot timeseries key: symbol:AAPL|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20201016T000000|right:C|strike:100

In [21]:
f.timeseries

,open,high,low,close,volume,bid_size,closebid,ask_size,closeask,midpoint,weighted_midpoint
datetime,,,,,,,,,,,
2020-08-31,27.48,31.73,27.48,30.50,1937,2,29.60,9,31.40,30.500,31.072727
2020-09-01,33.50,35.43,31.80,35.27,462,57,33.95,1,35.45,34.700,33.975862
2020-09-02,37.73,37.73,29.00,32.73,3310,10,31.60,10,33.70,32.650,32.650000
2020-09-03,28.80,30.15,23.15,23.50,901,4,23.00,2,25.00,24.000,23.666667
2020-09-04,23.15,25.30,15.80,23.40,2586,16,22.80,10,23.40,23.100,23.030769
2020-09-08,17.00,21.30,15.93,15.93,1127,2,15.25,1,16.25,15.750,15.583333
2020-09-09,18.80,20.50,18.00,19.12,377,56,18.75,55,19.05,18.900,18.898649
2020-09-10,20.70,20.75,14.95,15.80,2566,20,15.20,1,16.35,15.775,15.254762
2020-09-11,16.60,16.60,12.60,14.20,2085,70,13.95,12,14.25,14.100,13.993902
2020-09-14,16.10,17.10,14.50,16.80,1200,16,16.45,20,16.70,16.575,16.588889
2020-09-15,18.72,19.00,15.25,16.76,995,64,16.60,26,16.80,16.700,16.657778
2020-09-16,16.70,16.70,13.92,14.00,1197,17,13.80,13,14.00,13.900,13.886667
2020-09-17,12.96,13.83,11.50,12.45,1523,11,12.25,138,12.60,12.425,12.574161
2020-09-18,12.40,12.40,9.50,9.60,2855,60,9.55,60,9.85,9.700,9.700000
2020-09-21,8.10,12.18,7.50,12.18,2365,55,12.10,55,12.35,12.225,12.225000
2020-09-22,13.85,13.85,11.35,13.35,1681,91,13.05,21,13.35,13.200,13.106250
2020-09-23,12.90,13.30,9.49,9.77,988,18,9.65,18,9.95,9.800,9.800000
2020-09-24,8.45,11.85,8.32,10.36,908,10,10.20,31,10.40,10.300,10.351220
2020-09-25,10.68,13.40,9.95,13.33,853,70,13.10,30,13.45,13.275,13.205000
2020-09-28,15.81,15.81,13.70,15.45,426,141,15.35,20,15.55,15.450,15.374845

In [19]:
LIST_DATE_CACHE.clear()

2

In [1]:
from dbase.DataAPI.ThetaData.patches.main import ThetaDataPatchProcessor
from dbase.DataAPI.ThetaData.patches import ThetaDataPatchProcessor as ThetaDataPatchProcessorV3
ThetaDataPatchProcessorV3 == ThetaDataPatchProcessor
# ThetaDataPatchProcessor.PATCH_FUNCTIONS

/Users/chiemelienwanisobi/miniconda3/envs/openbb_new_use/lib/python3.11/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

2026-04-26 20:49:07 trade.helpers.Logging INFO: Logging Root Directory: /Users/chiemelienwanisobi/cloned_repos/FinanceDatabase/logs
2026-04-26 20:49:07 [test] trade.helpers.clear_cache INFO: No expired caches to delete on 2026-04-26.
2026-04-26 20:49:08 [test] dbase.DataAPI.ThetaData.proxy INFO: Refreshed proxy URL: http://34.229.99.136:5500/thetadata
2026-04-26 20:49:08 [test] dbase.DataAPI.ThetaData.proxy INFO: Using Proxy URL: http://34.229.99.136:5500/thetadata
Registering patch for list_dates
Registering patch for list_dates with function _remove_incorrect_date_for_option

True

In [ ]:
ThetaDataPatchProcessor.setup()

Registering patch for list_dates with function _remove_incorrect_date_for_option

True

In [5]:
ThetaDataPatchProcessor.PATCH_FUNCTIONS

{'list_dates': [<function dbase.DataAPI.ThetaData.patches.p1._remove_incorrect_date_for_option(result: Union[List[str], numpy.ndarray], symbol: str, exp: str, right: str, strike: float, *args, **kwargs) -> Union[List[str], numpy.ndarray]>]}

In [6]:

ThetaDataPatchProcessorV3.PATCH_FUNCTIONS

{'list_dates': [<function dbase.DataAPI.ThetaData.patches.p1._remove_incorrect_date_for_option(result: Union[List[str], numpy.ndarray], symbol: str, exp: str, right: str, strike: float, *args, **kwargs) -> Union[List[str], numpy.ndarray]>]}

In [56]:
ThetaDataPatchProcessor.setup()

Registering patch for list_dates with function _remove_incorrect_date_for_option

In [17]:
from typing import List, Union
import numpy as np

LIST_DATES_REMOVAL_BUCKET = {
    ("AAPL", "2020-10-16", "C", 96.25): "2020-08-25",
}



def _remove_incorrect_date(d: Union[List[str], np.ndarray], dt: str) -> List[str]:

    """
    Remove the incorrect date from the list of dates.
    Parameters    ----------
    d : List[str] or np.ndarray
        List of dates to be filtered.
    dt : str
        The date to be removed from the list.
    Returns    -------
    List[str]
        The list of dates with the incorrect date removed."""
    if dt in d:
        if isinstance(d, np.ndarray):
            d = d[d != dt]
        else:
            d.remove(dt)
        
    return d

def _remove_incorrect_date_for_option(
    symbol: str,
    exp: str,
    right: str,
    strike: float,
    d: Union[List[str], np.ndarray] = None,
    **kwargs
) -> Union[List[str], np.ndarray]:
    """
    Remove the incorrect date from the list of dates for a specific option contract.
    Parameters    ----------
    d : List[str] or np.ndarray
        List of dates to be filtered.
    symbol : str
        The symbol of the option contract.
    exp : str
        The expiration date of the option contract.
    right : str
        The right of the option contract (C or P).
    strike : float
        The strike price of the option contract.
    Returns    -------
    List[str] or np.ndarray
        The list of dates with the incorrect date removed."""
    
    key = (symbol, exp, right, strike)
    if d is None:
        d = list_dates(
            symbol=symbol,
            exp=exp,
            right=right,
            strike=strike,
        )
    
    if key in LIST_DATES_REMOVAL_BUCKET:
        dt = LIST_DATES_REMOVAL_BUCKET[key]
        return _remove_incorrect_date(d, dt)
    
    return d

# d = _remove_incorrect_date(d, "2020-08-25")
# d

In [33]:
import inspect
sig = inspect.signature(_remove_incorrect_date_for_option)
sig.parameters['kwargs'].kind

In [34]:
from pathlib import Path

NameError: name '__file__' is not defined

In [ ]:
from typing import Callable, Dict, List
class ThetaDataPatchProcessor:
    """
    Class responsible for applying patches to ThetaData API functions to handle known data issues.
    """
    PATCH_FUNCTIONS: Dict[str, List[Callable]] = {}

    @classmethod
    def register_patch(cls, func_name: str, patch_func: Callable):
        """
        Register a patch function for a specific ThetaData API function.
        Parameters    ----------
        func_name : str
            The name of the ThetaData API function to patch.
        patch_func : Callable
            The patch function to apply to the specified API function.
        """
        if func_name not in cls.PATCH_FUNCTIONS:
            cls.PATCH_FUNCTIONS[func_name] = []
        cls.PATCH_FUNCTIONS[func_name].append(patch_func)

    @classmethod
    def apply_patches(cls, func_name: str, *args, **kwargs):
        """
        Apply all registered patches for a specific ThetaData API function.
        Parameters    ----------
        func_name : str
            The name of the ThetaData API function to apply patches to.
        *args
            Positional arguments to pass to the patch functions.
        **kwargs
            Keyword arguments to pass to the patch functions.
        Returns    -------
        The result of applying the patches, if any, or None if no patches are registered."""
        if func_name in cls.PATCH_FUNCTIONS:
            for patch_func in cls.PATCH_FUNCTIONS[func_name]:
                result = patch_func(*args, **kwargs)
                if result is not None:
                    return result
        return None

In [25]:
c = list_contracts(
    symbol='AAPL',
    start_date='2020-08-25',
)
c[c["strike"] == 96.25]

2026-04-26 19:46:00 [test] dbase.DataAPI.ThetaData.switcher INFO: Switcher call list_contracts -> v2

      root  expiration  strike right
2994  AAPL    20200828   96.25     C
2995  AAPL    20200828   96.25     P
3008  AAPL    20200918   96.25     C
3009  AAPL    20200918   96.25     P
3024  AAPL    20201120   96.25     P
3025  AAPL    20201120   96.25     C
3074  AAPL    20210416   96.25     P
3075  AAPL    20210416   96.25     C
3890  AAPL    20200911   96.25     C
3891  AAPL    20200911   96.25     P
3898  AAPL    20201002   96.25     C
3899  AAPL    20201002   96.25     P
3935  AAPL    20210115   96.25     P
3936  AAPL    20210115   96.25     C
3958  AAPL    20210319   96.25     P
3959  AAPL    20210319   96.25     C
4178  AAPL    20200904   96.25     C
4179  AAPL    20200904   96.25     P
4184  AAPL    20200925   96.25     C
4185  AAPL    20200925   96.25     P
4198  AAPL    20201016   96.25     C
4199  AAPL    20201016   96.25     P

In [8]:
d

array(['2020-08-25', '2020-08-31', '2020-09-01', '2020-09-02',
       '2020-09-03', '2020-09-04', '2020-09-08', '2020-09-09',
       '2020-09-10', '2020-09-11', '2020-09-14', '2020-09-15',
       '2020-09-16', '2020-09-17', '2020-09-18', '2020-09-21',
       '2020-09-22', '2020-09-23', '2020-09-24', '2020-09-25',
       '2020-09-28', '2020-09-29', '2020-09-30', '2020-10-01',
       '2020-10-02', '2020-10-05', '2020-10-06', '2020-10-07',
       '2020-10-08', '2020-10-09', '2020-10-12', '2020-10-13',
       '2020-10-14', '2020-10-15', '2020-10-16'], dtype=object)